# Generated by Django 3.1.2 on 2020-11-26 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.ImageField(height_field=600, null=True, upload_to='', width_field=600)),
                ('description', models.TextField(null=True)),
                ('opsi_wakaf', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('kategori', models.CharField(choices=[('Galeri Foto / Gambar', 'Galeri Foto / Gambar'), ('URL', 'URL'), ('Katalog File', 'Katalog File'), ('PodCast / Audio', 'PodCast / Audio'), ('WebToon', 'WebToon'), ('Fotografi', 'Fotografi'), ('Ilustrasi', 'Ilustrasi'), ('Software', 'Software')], max_length=100)),
                ('konten_isi', models.BinaryField(null=True)),
                ('konten_bonus_tipe', models.CharField(choices=[('Galeri Foto / Gambar', 'Galeri Foto / Gambar'), ('URL', 'URL'), ('Katalog File', 'Katalog File'), ('PodCast / Audio', 'PodCast / Audio'), ('WebToon', 'WebToon'), ('Fotografi', 'Fotografi'), ('Ilustrasi', 'Ilustrasi'), ('Software', 'Software')], max_length=100, null=True)),
                ('konten_bonus_isi', models.BinaryField(null=True)),
                ('featured', models.BooleanField()),
                ('frontpage', models.BooleanField()),
                ('review', models.TextField()),
                ('status', models.CharField(choices=[('proposal', 'proposal'), ('disetujui', 'disetujui'), ('ditolak', 'ditolak'), ('bermasalah', 'bermasalah')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('kota', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
