# Generated by Django 3.1.2 on 2020-11-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201126_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='downloadable',
            field=models.BooleanField(default=False),
        ),
    ]
